version: '3.8'

services:
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    env_file: 
      - app.env
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres-db:
    driver: local